"""enzyme info

Revision ID: 396785072a1f
Revises: 26259a28fa2e
Create Date: 2013-04-11 16:51:34.082730

"""

# revision identifiers, used by Alembic.
revision = '396785072a1f'
down_revision = '26259a28fa2e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'movies', sa.Column('vcodec', sa.String(), nullable=True))
    op.add_column(u'movies', sa.Column('vwidth', sa.Integer(), nullable=True))
    op.add_column(u'movies', sa.Column('acodec', sa.String(), nullable=True))
    op.add_column(u'tv_episodes', sa.Column('vcodec', sa.String(), nullable=True))
    op.add_column(u'tv_episodes', sa.Column('vwidth', sa.Integer(), nullable=True))
    op.add_column(u'tv_episodes', sa.Column('acodec', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'tv_episodes', 'acodec')
    op.drop_column(u'tv_episodes', 'vwidth')
    op.drop_column(u'tv_episodes', 'vcodec')
    op.drop_column(u'movies', 'acodec')
    op.drop_column(u'movies', 'vwidth')
    op.drop_column(u'movies', 'vcodec')
    ### end Alembic commands ###
